services:
  python-app:
    build:
      context: .
    container_name: python-app
    restart: unless-stopped
    init: true
    ports:
      - "80:80"  # Cambiado de 8000:8000 a 80:80
    networks:
      - appnet
    volumes:
      - ./static:/app/static
      - ./db.sqlite3:/app/db.sqlite3

networks:
  appnet:
    driver: bridge
